GET http://localhost:3931/


### Students

GET http://localhost:3931/students


###


POST http://localhost:3931/students
Content-Type: application/json

{
    "name": "Essa",
    "gender": "m",
    "courseID": 2
}
